Server:
  RunMode           : debug
  HttpPort          : 8000
  ReadTimeOut       : 60
  WriteTimeOut      : 60

App:
  DefaultPageSize     : 10
  MaxPageSize         : 100
  LogSavePath         : storage/logs
  LogFileName         : app
  LogFileExt          : .log

Database:
  DBType              : mysql
  Username            : root
  Password            : Mibx@2020
  Host                : 123.57.156.250:3306
  DBName              : blog_service
  TablePrefix         : blog_
  Charset             : utf8
  ParseTime           : True
  MaxIdleConns        : 10
  MaxOpenConns        : 30