Server:
  RunMode           : debug
  HttpPort          : 8000
  ReadTimeOut       : 60
  WriteTimeOut      : 60

App:
  DefaultPageSize     : 10
  MaxPageSize         : 100
  LogSavePath         : storage/logs
  LogFileName         : app
  LogFileExt          : .log
  UploadSavePath      : storage/uploads
  UploadServerUrl     : http://127.0.0.1:8000/static
  UploadImageMaxSize  : 5 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png

Database:
  DBType              : mysql
  Username            : root
  Password            : 19861029
  Host                : 152.136.253.191:3306
  DBName              : blog_service
  TablePrefix         : blog_
  Charset             : utf8
  ParseTime           : True
  MaxIdleConns        : 10
  MaxOpenConns        : 30

JWT:
  Secret              : reation
  Issuer              : blog-service
  Expire              : 7200

Email:
  Host: smtp.163.com
  Port: 465
  UserName: reation_11
  Password: Hai*isbest
  IsSSL: true
  From: reation_11@163.com
  To:
    - 123652149@qq.com
Kafka:
  Host:
    - 152.136.253.191:9092
    - 49.233.55.149:9092
    - 81.70.211.73:9092
